services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: UniverseDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  unispace-api:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=UniverseDb;Username=user;Password=password
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  pgdata:
